services:
  db:
    image: postgres:16-alpine
    container_name: clinic_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres} 
      - POSTGRES_DB=${POSTGRES_DB:-clinic_db} 
    ports:
      - "5345:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER:-postgres} -d $${POSTGRES_DB:-clinic_db}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks: 
      - my_network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5056:5050"
    depends_on:
      - db

  backend:
    build:
      context: ./FastAPI 
    container_name: clinic_backend
    volumes:
      - ./FastAPI:/app 
    ports:
      - "8101:8000"
    env_file:
      - ./FastAPI/.env 
    depends_on:
      db:
        condition: service_healthy
    networks:
      - my_network

  streamlit:
    build:
      context: ./Streamlit 
    container_name: streamlit_frontend_app
    # command: >
    #   streamlit run app.py
    #   --server.port=8506
    #   --server.address=0.0.0.0
    #   --server.enableCORS=false
    #   --server.enableXsrfProtection=false
    ports:
      - "8506:8501" 
    volumes:
      - ./Streamlit:/app 
    networks: 
      - my_network

volumes:
  postgres_data:

networks:
  my_network:
    driver: bridge